### ISSUE TITLE
Some rego policies does not work

### ISSUE THREAD

**Issue by juadk** [kubewarden/rego-policies-library#23]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I wanted to test some Rego policies because we released them recently and I have issue with the first three one  of my [test](https://github.com/kubewarden/kubewarden-end-to-end-tests/issues/149).

https://artifacthub.io/packages/kubewarden/kubewarden-rego-policies-library/block-workloads-created-without-specifying-namespace
https://artifacthub.io/packages/kubewarden/kubewarden-rego-policies-library/container-block-sysctl
https://artifacthub.io/packages/kubewarden/kubewarden-rego-policies-library/container-running-as-root

But when I install and apply the policies, I can still create deployment with sysctl value or container running as root.

```
root@ja-test-droplet-gvizcm-rancher-server:~# kubectl get cap
NAME                        POLICY SERVER   MUTATING   BACKGROUNDAUDIT   MODE      OBSERVED MODE   STATUS   AGE
container-block-sysctl      default         false      true              protect   protect         active   37m
container-running-as-root   default         false      true              protect   protect         active   105s
```
I use this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
  ```
There is nothing relevant in the policy server log.

In the controller log, I see this error but I don't know if it is relevant:
```
{"level":"info","ts":"2025-03-20T10:03:26Z","logger":"policyserver-webhook","msg":"Defaulting PolicyServer","name":"default"}
{"level":"info","ts":"2025-03-20T10:03:26Z","logger":"policyserver-webhook","msg":"Validating PolicyServer create","name":"default"}
{"level":"info","ts":"2025-03-20T10:04:02Z","logger":"clusteradmissionpolicy-webhook","msg":"Defaulting ClusterAdmissionPolicy","name":"container-running-as-root"}
{"level":"info","ts":"2025-03-20T10:04:02Z","logger":"clusteradmissionpolicy-webhook","msg":"Validating ClusterAdmissionPolicy creation","name":"container-running-as-root"}
{"level":"error","ts":"2025-03-20T10:04:03Z","msg":"Reconciler error","controller":"clusteradmissionpolicy","controllerGroup":"policies.kubewarden.io","controllerKind":"ClusterAdmissionPolicy","ClusterAdmissionPolicy":{"name":"container-running-as-root"},"namespace":"","name":"container-running-as-root","reconcileID":"0d6bc699-3852-4a90-99eb-c47afff29dd0","error":"update admission policy status error: Operation cannot be fulfilled on clusteradmissionpolicies.policies.kubewarden.io \"container-running-as-root\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:341\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249"}
{"level":"info","ts":"2025-03-20T10:05:53Z","logger":"clusteradmissionpolicy-webhook","msg":"Defaulting ClusterAdmissionPolicy","name":"container-block-sysctl"}
{"level":"info","ts":"2025-03-20T10:05:53Z","logger":"clusteradmissionpolicy-webhook","msg":"Validating ClusterAdmissionPolicy creation","name":"container-block-sysctl"}
```

### Expected Behavior

The deployment should be rejected by the policy server.

### Environment

```markdown
- Architecture: k3d
- Versions: kubewarden-controller:v1.22.0 and policy-server:v1.22.0
```
