### ISSUE TITLE
Issue with containers-block-specific-image-names policy

### ISSUE THREAD

**Issue by juadk** [kubewarden/rego-policies-library#29]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

- Install the 1.0.1 policy version with kwctl
`kwctl pull ghcr.io/kubewarden/policies/containers-block-specific-image-names:v1.0.1`
- Customize and apply the policy
```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: software-supply-chain
    io.kubewarden.policy.severity: high
  name: containers-block-specific-image-names
spec:
  module: registry://ghcr.io/kubewarden/policies/containers-block-specific-image-names:v1.0.1
  settings:
    parameters:
      restricted_image_names:
        - "nginx"
  rules:
  - apiGroups:
    - batch
    apiVersions:
    - v1
    resources:
    - cronjobs
    - jobs
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - daemonsets
    - deployments
    - statefulsets
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
    - UPDATE
  mutating: false
```

Waiting for the policy to be active in protect mode:
```
NAME                                    POLICY SERVER   MUTATING   BACKGROUNDAUDIT   MODE      OBSERVED MODE   STATUS   AGE
containers-block-specific-image-names   default         false      true              protect   protect         active   4m14s
```

Then trying to push this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
 ```
deployment.apps/nginx-deployment created

If I understand correctly, the deployment should have been denied due to the nginx image usage.

### Expected Behavior

Deployment denied by the policy

**Comment by fabriziosestito** [comment]
Try removing the  `parameters` key, then it should work:

```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: software-supply-chain
    io.kubewarden.policy.severity: high
  name: containers-block-specific-image-names
spec:
  module: registry://ghcr.io/kubewarden/policies/containers-block-specific-image-names:v1.0.1
  settings:
      restricted_image_names:
        - "nginx"
  rules:
  - apiGroups:
    - batch
    apiVersions:
    - v1
    resources:
    - cronjobs
    - jobs
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - daemonsets
    - deployments
    - statefulsets
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
    - UPDATE
  mutating: false
```
