### ISSUE TITLE
Fix README settings / parameters section

### ISSUE THREAD

**Issue by juadk** [kubewarden/rego-policies-library#30]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Issue spotted in this [issue](https://github.com/kubewarden/rego-policies-library/issues/29)

In the settings section, we can see:
```
  settings:
    parameters:
      - name: restricted_image_names
        type: array
        required: true
        value:
      - name: exclude_namespaces
        type: array
        required: false
        value:
      - name: exclude_label_key
        type: string
        required: false
        value:
      - name: exclude_label_value
        type: string
        required: false
        value:
```

And if you want to make it work, policy has to be configured like this:
```
  settings:
    restricted_image_names:
      - "nginx"
 ```
parameters should not be written in any case.

I think the current README version is not clear enough and may confuse people, especially Kubewarden beginners.

### Expected Behavior

Giving a clear example on how to use the policy in the README.
